# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/aeri/git/UnrealEngine
GAMEPROJECTFILE =/home/aeri/freelance/gitcoin/AlgorandDemo/AlgorandDemo.uproject

TARGETS = \
	AlgorandDemo-Linux-Debug  \
	AlgorandDemo-Linux-DebugGame  \
	AlgorandDemo-Linux-Shipping  \
	AlgorandDemo-Linux-Test  \
	AlgorandDemo \
	AlgorandDemoEditor-Linux-Debug  \
	AlgorandDemoEditor-Linux-DebugGame  \
	AlgorandDemoEditor-Linux-Shipping  \
	AlgorandDemoEditor-Linux-Test  \
	AlgorandDemoEditor \
	BenchmarkTool-Linux-Debug  \
	BenchmarkTool-Linux-DebugGame  \
	BenchmarkTool-Linux-Shipping  \
	BenchmarkTool-Linux-Test  \
	BenchmarkTool \
	BlankProgram-Linux-Debug  \
	BlankProgram-Linux-DebugGame  \
	BlankProgram-Linux-Shipping  \
	BlankProgram-Linux-Test  \
	BlankProgram \
	BuildPatchTool-Linux-Debug  \
	BuildPatchTool-Linux-DebugGame  \
	BuildPatchTool-Linux-Shipping  \
	BuildPatchTool-Linux-Test  \
	BuildPatchTool \
	ChaosVisualDebugger-Linux-Debug  \
	ChaosVisualDebugger-Linux-DebugGame  \
	ChaosVisualDebugger-Linux-Shipping  \
	ChaosVisualDebugger-Linux-Test  \
	ChaosVisualDebugger \
	CrashReportClient-Linux-Debug  \
	CrashReportClient-Linux-DebugGame  \
	CrashReportClient-Linux-Shipping  \
	CrashReportClient-Linux-Test  \
	CrashReportClient \
	CrashReportClientEditor-Linux-Debug  \
	CrashReportClientEditor-Linux-DebugGame  \
	CrashReportClientEditor-Linux-Shipping  \
	CrashReportClientEditor-Linux-Test  \
	CrashReportClientEditor \
	DatasmithUE4ArchiCAD-Linux-Debug  \
	DatasmithUE4ArchiCAD-Linux-DebugGame  \
	DatasmithUE4ArchiCAD-Linux-Shipping  \
	DatasmithUE4ArchiCAD-Linux-Test  \
	DatasmithUE4ArchiCAD \
	DatasmithArchiCAD-Linux-Debug  \
	DatasmithArchiCAD-Linux-DebugGame  \
	DatasmithArchiCAD-Linux-Shipping  \
	DatasmithArchiCAD-Linux-Test  \
	DatasmithArchiCAD \
	DatasmithCADWorker-Linux-Debug  \
	DatasmithCADWorker-Linux-DebugGame  \
	DatasmithCADWorker-Linux-Shipping  \
	DatasmithCADWorker-Linux-Test  \
	DatasmithCADWorker \
	DatasmithFacadeCSharp-Linux-Debug  \
	DatasmithFacadeCSharp-Linux-DebugGame  \
	DatasmithFacadeCSharp-Linux-Shipping  \
	DatasmithFacadeCSharp-Linux-Test  \
	DatasmithFacadeCSharp \
	DatasmithMax2016-Linux-Debug  \
	DatasmithMax2016-Linux-DebugGame  \
	DatasmithMax2016-Linux-Shipping  \
	DatasmithMax2016-Linux-Test  \
	DatasmithMax2016 \
	DatasmithMax2017-Linux-Debug  \
	DatasmithMax2017-Linux-DebugGame  \
	DatasmithMax2017-Linux-Shipping  \
	DatasmithMax2017-Linux-Test  \
	DatasmithMax2017 \
	DatasmithMax2018-Linux-Debug  \
	DatasmithMax2018-Linux-DebugGame  \
	DatasmithMax2018-Linux-Shipping  \
	DatasmithMax2018-Linux-Test  \
	DatasmithMax2018 \
	DatasmithMax2019-Linux-Debug  \
	DatasmithMax2019-Linux-DebugGame  \
	DatasmithMax2019-Linux-Shipping  \
	DatasmithMax2019-Linux-Test  \
	DatasmithMax2019 \
	DatasmithMax2020-Linux-Debug  \
	DatasmithMax2020-Linux-DebugGame  \
	DatasmithMax2020-Linux-Shipping  \
	DatasmithMax2020-Linux-Test  \
	DatasmithMax2020 \
	DatasmithMax2021-Linux-Debug  \
	DatasmithMax2021-Linux-DebugGame  \
	DatasmithMax2021-Linux-Shipping  \
	DatasmithMax2021-Linux-Test  \
	DatasmithMax2021 \
	DatasmithMax2022-Linux-Debug  \
	DatasmithMax2022-Linux-DebugGame  \
	DatasmithMax2022-Linux-Shipping  \
	DatasmithMax2022-Linux-Test  \
	DatasmithMax2022 \
	DatasmithNavisworks2019-Linux-Debug  \
	DatasmithNavisworks2019-Linux-DebugGame  \
	DatasmithNavisworks2019-Linux-Shipping  \
	DatasmithNavisworks2019-Linux-Test  \
	DatasmithNavisworks2019 \
	DatasmithNavisworks2020-Linux-Debug  \
	DatasmithNavisworks2020-Linux-DebugGame  \
	DatasmithNavisworks2020-Linux-Shipping  \
	DatasmithNavisworks2020-Linux-Test  \
	DatasmithNavisworks2020 \
	DatasmithNavisworks2021-Linux-Debug  \
	DatasmithNavisworks2021-Linux-DebugGame  \
	DatasmithNavisworks2021-Linux-Shipping  \
	DatasmithNavisworks2021-Linux-Test  \
	DatasmithNavisworks2021 \
	DatasmithNavisworks2022-Linux-Debug  \
	DatasmithNavisworks2022-Linux-DebugGame  \
	DatasmithNavisworks2022-Linux-Shipping  \
	DatasmithNavisworks2022-Linux-Test  \
	DatasmithNavisworks2022 \
	DatasmithRevit2018-Linux-Debug  \
	DatasmithRevit2018-Linux-DebugGame  \
	DatasmithRevit2018-Linux-Shipping  \
	DatasmithRevit2018-Linux-Test  \
	DatasmithRevit2018 \
	DatasmithRevit2019-Linux-Debug  \
	DatasmithRevit2019-Linux-DebugGame  \
	DatasmithRevit2019-Linux-Shipping  \
	DatasmithRevit2019-Linux-Test  \
	DatasmithRevit2019 \
	DatasmithRevit2020-Linux-Debug  \
	DatasmithRevit2020-Linux-DebugGame  \
	DatasmithRevit2020-Linux-Shipping  \
	DatasmithRevit2020-Linux-Test  \
	DatasmithRevit2020 \
	DatasmithRevit2021-Linux-Debug  \
	DatasmithRevit2021-Linux-DebugGame  \
	DatasmithRevit2021-Linux-Shipping  \
	DatasmithRevit2021-Linux-Test  \
	DatasmithRevit2021 \
	DatasmithRevit2022-Linux-Debug  \
	DatasmithRevit2022-Linux-DebugGame  \
	DatasmithRevit2022-Linux-Shipping  \
	DatasmithRevit2022-Linux-Test  \
	DatasmithRevit2022 \
	DatasmithRhino6-Linux-Debug  \
	DatasmithRhino6-Linux-DebugGame  \
	DatasmithRhino6-Linux-Shipping  \
	DatasmithRhino6-Linux-Test  \
	DatasmithRhino6 \
	DatasmithRhino7-Linux-Debug  \
	DatasmithRhino7-Linux-DebugGame  \
	DatasmithRhino7-Linux-Shipping  \
	DatasmithRhino7-Linux-Test  \
	DatasmithRhino7 \
	DatasmithSDK-Linux-Debug  \
	DatasmithSDK-Linux-DebugGame  \
	DatasmithSDK-Linux-Shipping  \
	DatasmithSDK-Linux-Test  \
	DatasmithSDK \
	DatasmithSketchUpRuby2019-Linux-Debug  \
	DatasmithSketchUpRuby2019-Linux-DebugGame  \
	DatasmithSketchUpRuby2019-Linux-Shipping  \
	DatasmithSketchUpRuby2019-Linux-Test  \
	DatasmithSketchUpRuby2019 \
	DatasmithSketchUpRuby2020-Linux-Debug  \
	DatasmithSketchUpRuby2020-Linux-DebugGame  \
	DatasmithSketchUpRuby2020-Linux-Shipping  \
	DatasmithSketchUpRuby2020-Linux-Test  \
	DatasmithSketchUpRuby2020 \
	DatasmithSketchUpRuby2021-Linux-Debug  \
	DatasmithSketchUpRuby2021-Linux-DebugGame  \
	DatasmithSketchUpRuby2021-Linux-Shipping  \
	DatasmithSketchUpRuby2021-Linux-Test  \
	DatasmithSketchUpRuby2021 \
	DatasmithSolidworks2021-Linux-Debug  \
	DatasmithSolidworks2021-Linux-DebugGame  \
	DatasmithSolidworks2021-Linux-Shipping  \
	DatasmithSolidworks2021-Linux-Test  \
	DatasmithSolidworks2021 \
	HeadlessChaos-Linux-Debug  \
	HeadlessChaos-Linux-DebugGame  \
	HeadlessChaos-Linux-Shipping  \
	HeadlessChaos-Linux-Test  \
	HeadlessChaos \
	HeadlessChaosPerf-Linux-Debug  \
	HeadlessChaosPerf-Linux-DebugGame  \
	HeadlessChaosPerf-Linux-Shipping  \
	HeadlessChaosPerf-Linux-Test  \
	HeadlessChaosPerf \
	UnrealLaunchDaemon-Linux-Debug  \
	UnrealLaunchDaemon-Linux-DebugGame  \
	UnrealLaunchDaemon-Linux-Shipping  \
	UnrealLaunchDaemon-Linux-Test  \
	UnrealLaunchDaemon \
	LiveCodingConsole-Linux-Debug  \
	LiveCodingConsole-Linux-DebugGame  \
	LiveCodingConsole-Linux-Shipping  \
	LiveCodingConsole-Linux-Test  \
	LiveCodingConsole \
	DsymExporter-Linux-Debug  \
	DsymExporter-Linux-DebugGame  \
	DsymExporter-Linux-Shipping  \
	DsymExporter-Linux-Test  \
	DsymExporter \
	UE4EditorServices-Linux-Debug  \
	UE4EditorServices-Linux-DebugGame  \
	UE4EditorServices-Linux-Shipping  \
	UE4EditorServices-Linux-Test  \
	UE4EditorServices \
	UnrealAtoS-Linux-Debug  \
	UnrealAtoS-Linux-DebugGame  \
	UnrealAtoS-Linux-Shipping  \
	UnrealAtoS-Linux-Test  \
	UnrealAtoS \
	ShaderCompileWorker-Linux-Debug  \
	ShaderCompileWorker-Linux-DebugGame  \
	ShaderCompileWorker-Linux-Shipping  \
	ShaderCompileWorker-Linux-Test  \
	ShaderCompileWorker \
	SlateViewer-Linux-Debug  \
	SlateViewer-Linux-DebugGame  \
	SlateViewer-Linux-Shipping  \
	SlateViewer-Linux-Test  \
	SlateViewer \
	SwitchboardListener-Linux-Debug  \
	SwitchboardListener-Linux-DebugGame  \
	SwitchboardListener-Linux-Shipping  \
	SwitchboardListener-Linux-Test  \
	SwitchboardListener \
	TestPAL-Linux-Debug  \
	TestPAL-Linux-DebugGame  \
	TestPAL-Linux-Shipping  \
	TestPAL-Linux-Test  \
	TestPAL \
	TextureShareSDK-Linux-Debug  \
	TextureShareSDK-Linux-DebugGame  \
	TextureShareSDK-Linux-Shipping  \
	TextureShareSDK-Linux-Test  \
	TextureShareSDK \
	UnrealCEFSubProcess-Linux-Debug  \
	UnrealCEFSubProcess-Linux-DebugGame  \
	UnrealCEFSubProcess-Linux-Shipping  \
	UnrealCEFSubProcess-Linux-Test  \
	UnrealCEFSubProcess \
	UnrealFileServer-Linux-Debug  \
	UnrealFileServer-Linux-DebugGame  \
	UnrealFileServer-Linux-Shipping  \
	UnrealFileServer-Linux-Test  \
	UnrealFileServer \
	UnrealFrontend-Linux-Debug  \
	UnrealFrontend-Linux-DebugGame  \
	UnrealFrontend-Linux-Shipping  \
	UnrealFrontend-Linux-Test  \
	UnrealFrontend \
	UnrealHeaderTool-Linux-Debug  \
	UnrealHeaderTool-Linux-DebugGame  \
	UnrealHeaderTool-Linux-Shipping  \
	UnrealHeaderTool-Linux-Test  \
	UnrealHeaderTool \
	UnrealInsights-Linux-Debug  \
	UnrealInsights-Linux-DebugGame  \
	UnrealInsights-Linux-Shipping  \
	UnrealInsights-Linux-Test  \
	UnrealInsights \
	UnrealLightmass-Linux-Debug  \
	UnrealLightmass-Linux-DebugGame  \
	UnrealLightmass-Linux-Shipping  \
	UnrealLightmass-Linux-Test  \
	UnrealLightmass \
	UnrealMultiUserServer-Linux-Debug  \
	UnrealMultiUserServer-Linux-DebugGame  \
	UnrealMultiUserServer-Linux-Shipping  \
	UnrealMultiUserServer-Linux-Test  \
	UnrealMultiUserServer \
	UnrealPak-Linux-Debug  \
	UnrealPak-Linux-DebugGame  \
	UnrealPak-Linux-Shipping  \
	UnrealPak-Linux-Test  \
	UnrealPak \
	UnrealRecoverySvc-Linux-Debug  \
	UnrealRecoverySvc-Linux-DebugGame  \
	UnrealRecoverySvc-Linux-Shipping  \
	UnrealRecoverySvc-Linux-Test  \
	UnrealRecoverySvc \
	UnrealVersionSelector-Linux-Debug  \
	UnrealVersionSelector-Linux-DebugGame  \
	UnrealVersionSelector-Linux-Shipping  \
	UnrealVersionSelector-Linux-Test  \
	UnrealVersionSelector \
	BootstrapPackagedGame-Linux-Debug  \
	BootstrapPackagedGame-Linux-DebugGame  \
	BootstrapPackagedGame-Linux-Shipping  \
	BootstrapPackagedGame-Linux-Test  \
	BootstrapPackagedGame \
	UE4Client-Linux-Debug  \
	UE4Client-Linux-DebugGame  \
	UE4Client-Linux-Shipping  \
	UE4Client-Linux-Test  \
	UE4Client \
	UE4Editor-Linux-Debug  \
	UE4Editor-Linux-DebugGame  \
	UE4Editor-Linux-Shipping  \
	UE4Editor-Linux-Test  \
	UE4Editor \
	UE4Game-Linux-Debug  \
	UE4Game-Linux-DebugGame  \
	UE4Game-Linux-Shipping  \
	UE4Game-Linux-Test  \
	UE4Game \
	UE4Server-Linux-Debug  \
	UE4Server-Linux-DebugGame  \
	UE4Server-Linux-Shipping  \
	UE4Server-Linux-Test  \
	UE4Server\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/RunMono.sh" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool.exe"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass

StandardSet: RequiredTools UnrealFrontend UE4Editor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug UE4Editor-Linux-Debug


AlgorandDemo-Linux-Debug:
	 $(PROJECTBUILD) AlgorandDemo Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

AlgorandDemo-Linux-DebugGame:
	 $(PROJECTBUILD) AlgorandDemo Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

AlgorandDemo-Linux-Shipping:
	 $(PROJECTBUILD) AlgorandDemo Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

AlgorandDemo-Linux-Test:
	 $(PROJECTBUILD) AlgorandDemo Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

AlgorandDemo:
	 $(PROJECTBUILD) AlgorandDemo Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

AlgorandDemoEditor-Linux-Debug:
	 $(PROJECTBUILD) AlgorandDemoEditor Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

AlgorandDemoEditor-Linux-DebugGame:
	 $(PROJECTBUILD) AlgorandDemoEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

AlgorandDemoEditor-Linux-Shipping:
	 $(PROJECTBUILD) AlgorandDemoEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

AlgorandDemoEditor-Linux-Test:
	 $(PROJECTBUILD) AlgorandDemoEditor Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

AlgorandDemoEditor:
	 $(PROJECTBUILD) AlgorandDemoEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

BenchmarkTool-Linux-Debug:
	 $(BUILD) BenchmarkTool Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

BenchmarkTool-Linux-DebugGame:
	 $(BUILD) BenchmarkTool Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

BenchmarkTool-Linux-Shipping:
	 $(BUILD) BenchmarkTool Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

BenchmarkTool-Linux-Test:
	 $(BUILD) BenchmarkTool Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

BenchmarkTool:
	 $(BUILD) BenchmarkTool Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

BlankProgram-Linux-Debug:
	 $(BUILD) BlankProgram Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

BlankProgram-Linux-DebugGame:
	 $(BUILD) BlankProgram Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

BlankProgram-Linux-Shipping:
	 $(BUILD) BlankProgram Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

BlankProgram-Linux-Test:
	 $(BUILD) BlankProgram Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

BlankProgram:
	 $(BUILD) BlankProgram Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

BuildPatchTool-Linux-Debug:
	 $(BUILD) BuildPatchTool Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

BuildPatchTool-Linux-DebugGame:
	 $(BUILD) BuildPatchTool Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

BuildPatchTool-Linux-Shipping:
	 $(BUILD) BuildPatchTool Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

BuildPatchTool-Linux-Test:
	 $(BUILD) BuildPatchTool Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

BuildPatchTool:
	 $(BUILD) BuildPatchTool Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

ChaosVisualDebugger-Linux-Debug:
	 $(BUILD) ChaosVisualDebugger Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

ChaosVisualDebugger-Linux-DebugGame:
	 $(BUILD) ChaosVisualDebugger Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

ChaosVisualDebugger-Linux-Shipping:
	 $(BUILD) ChaosVisualDebugger Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

ChaosVisualDebugger-Linux-Test:
	 $(BUILD) ChaosVisualDebugger Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

ChaosVisualDebugger:
	 $(BUILD) ChaosVisualDebugger Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

CrashReportClient-Linux-Debug:
	 $(BUILD) CrashReportClient Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

CrashReportClient-Linux-DebugGame:
	 $(BUILD) CrashReportClient Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

CrashReportClient-Linux-Shipping:
	 $(BUILD) CrashReportClient Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

CrashReportClient-Linux-Test:
	 $(BUILD) CrashReportClient Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

CrashReportClient:
	 $(BUILD) CrashReportClient Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

CrashReportClientEditor-Linux-Debug:
	 $(BUILD) CrashReportClientEditor Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

CrashReportClientEditor-Linux-DebugGame:
	 $(BUILD) CrashReportClientEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

CrashReportClientEditor-Linux-Shipping:
	 $(BUILD) CrashReportClientEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

CrashReportClientEditor-Linux-Test:
	 $(BUILD) CrashReportClientEditor Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

CrashReportClientEditor:
	 $(BUILD) CrashReportClientEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithUE4ArchiCAD-Linux-Debug:
	 $(BUILD) DatasmithUE4ArchiCAD Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithUE4ArchiCAD-Linux-DebugGame:
	 $(BUILD) DatasmithUE4ArchiCAD Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithUE4ArchiCAD-Linux-Shipping:
	 $(BUILD) DatasmithUE4ArchiCAD Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithUE4ArchiCAD-Linux-Test:
	 $(BUILD) DatasmithUE4ArchiCAD Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithUE4ArchiCAD:
	 $(BUILD) DatasmithUE4ArchiCAD Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithArchiCAD-Linux-Debug:
	 $(BUILD) DatasmithArchiCAD Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithArchiCAD-Linux-DebugGame:
	 $(BUILD) DatasmithArchiCAD Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithArchiCAD-Linux-Shipping:
	 $(BUILD) DatasmithArchiCAD Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithArchiCAD-Linux-Test:
	 $(BUILD) DatasmithArchiCAD Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithArchiCAD:
	 $(BUILD) DatasmithArchiCAD Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithCADWorker-Linux-Debug:
	 $(BUILD) DatasmithCADWorker Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithCADWorker-Linux-DebugGame:
	 $(BUILD) DatasmithCADWorker Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithCADWorker-Linux-Shipping:
	 $(BUILD) DatasmithCADWorker Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithCADWorker-Linux-Test:
	 $(BUILD) DatasmithCADWorker Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithCADWorker:
	 $(BUILD) DatasmithCADWorker Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithFacadeCSharp-Linux-Debug:
	 $(BUILD) DatasmithFacadeCSharp Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithFacadeCSharp-Linux-DebugGame:
	 $(BUILD) DatasmithFacadeCSharp Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithFacadeCSharp-Linux-Shipping:
	 $(BUILD) DatasmithFacadeCSharp Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithFacadeCSharp-Linux-Test:
	 $(BUILD) DatasmithFacadeCSharp Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithFacadeCSharp:
	 $(BUILD) DatasmithFacadeCSharp Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2016-Linux-Debug:
	 $(BUILD) DatasmithMax2016 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2016-Linux-DebugGame:
	 $(BUILD) DatasmithMax2016 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2016-Linux-Shipping:
	 $(BUILD) DatasmithMax2016 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2016-Linux-Test:
	 $(BUILD) DatasmithMax2016 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2016:
	 $(BUILD) DatasmithMax2016 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2017-Linux-Debug:
	 $(BUILD) DatasmithMax2017 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2017-Linux-DebugGame:
	 $(BUILD) DatasmithMax2017 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2017-Linux-Shipping:
	 $(BUILD) DatasmithMax2017 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2017-Linux-Test:
	 $(BUILD) DatasmithMax2017 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2017:
	 $(BUILD) DatasmithMax2017 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2018-Linux-Debug:
	 $(BUILD) DatasmithMax2018 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2018-Linux-DebugGame:
	 $(BUILD) DatasmithMax2018 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2018-Linux-Shipping:
	 $(BUILD) DatasmithMax2018 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2018-Linux-Test:
	 $(BUILD) DatasmithMax2018 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2018:
	 $(BUILD) DatasmithMax2018 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2019-Linux-Debug:
	 $(BUILD) DatasmithMax2019 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2019-Linux-DebugGame:
	 $(BUILD) DatasmithMax2019 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2019-Linux-Shipping:
	 $(BUILD) DatasmithMax2019 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2019-Linux-Test:
	 $(BUILD) DatasmithMax2019 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2019:
	 $(BUILD) DatasmithMax2019 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2020-Linux-Debug:
	 $(BUILD) DatasmithMax2020 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2020-Linux-DebugGame:
	 $(BUILD) DatasmithMax2020 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2020-Linux-Shipping:
	 $(BUILD) DatasmithMax2020 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2020-Linux-Test:
	 $(BUILD) DatasmithMax2020 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2020:
	 $(BUILD) DatasmithMax2020 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2021-Linux-Debug:
	 $(BUILD) DatasmithMax2021 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2021-Linux-DebugGame:
	 $(BUILD) DatasmithMax2021 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2021-Linux-Shipping:
	 $(BUILD) DatasmithMax2021 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2021-Linux-Test:
	 $(BUILD) DatasmithMax2021 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2021:
	 $(BUILD) DatasmithMax2021 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2022-Linux-Debug:
	 $(BUILD) DatasmithMax2022 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2022-Linux-DebugGame:
	 $(BUILD) DatasmithMax2022 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2022-Linux-Shipping:
	 $(BUILD) DatasmithMax2022 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2022-Linux-Test:
	 $(BUILD) DatasmithMax2022 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2022:
	 $(BUILD) DatasmithMax2022 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2019-Linux-Debug:
	 $(BUILD) DatasmithNavisworks2019 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2019-Linux-DebugGame:
	 $(BUILD) DatasmithNavisworks2019 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2019-Linux-Shipping:
	 $(BUILD) DatasmithNavisworks2019 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2019-Linux-Test:
	 $(BUILD) DatasmithNavisworks2019 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2019:
	 $(BUILD) DatasmithNavisworks2019 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2020-Linux-Debug:
	 $(BUILD) DatasmithNavisworks2020 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2020-Linux-DebugGame:
	 $(BUILD) DatasmithNavisworks2020 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2020-Linux-Shipping:
	 $(BUILD) DatasmithNavisworks2020 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2020-Linux-Test:
	 $(BUILD) DatasmithNavisworks2020 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2020:
	 $(BUILD) DatasmithNavisworks2020 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2021-Linux-Debug:
	 $(BUILD) DatasmithNavisworks2021 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2021-Linux-DebugGame:
	 $(BUILD) DatasmithNavisworks2021 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2021-Linux-Shipping:
	 $(BUILD) DatasmithNavisworks2021 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2021-Linux-Test:
	 $(BUILD) DatasmithNavisworks2021 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2021:
	 $(BUILD) DatasmithNavisworks2021 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2022-Linux-Debug:
	 $(BUILD) DatasmithNavisworks2022 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2022-Linux-DebugGame:
	 $(BUILD) DatasmithNavisworks2022 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2022-Linux-Shipping:
	 $(BUILD) DatasmithNavisworks2022 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2022-Linux-Test:
	 $(BUILD) DatasmithNavisworks2022 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2022:
	 $(BUILD) DatasmithNavisworks2022 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2018-Linux-Debug:
	 $(BUILD) DatasmithRevit2018 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2018-Linux-DebugGame:
	 $(BUILD) DatasmithRevit2018 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2018-Linux-Shipping:
	 $(BUILD) DatasmithRevit2018 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2018-Linux-Test:
	 $(BUILD) DatasmithRevit2018 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2018:
	 $(BUILD) DatasmithRevit2018 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2019-Linux-Debug:
	 $(BUILD) DatasmithRevit2019 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2019-Linux-DebugGame:
	 $(BUILD) DatasmithRevit2019 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2019-Linux-Shipping:
	 $(BUILD) DatasmithRevit2019 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2019-Linux-Test:
	 $(BUILD) DatasmithRevit2019 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2019:
	 $(BUILD) DatasmithRevit2019 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2020-Linux-Debug:
	 $(BUILD) DatasmithRevit2020 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2020-Linux-DebugGame:
	 $(BUILD) DatasmithRevit2020 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2020-Linux-Shipping:
	 $(BUILD) DatasmithRevit2020 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2020-Linux-Test:
	 $(BUILD) DatasmithRevit2020 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2020:
	 $(BUILD) DatasmithRevit2020 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2021-Linux-Debug:
	 $(BUILD) DatasmithRevit2021 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2021-Linux-DebugGame:
	 $(BUILD) DatasmithRevit2021 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2021-Linux-Shipping:
	 $(BUILD) DatasmithRevit2021 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2021-Linux-Test:
	 $(BUILD) DatasmithRevit2021 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2021:
	 $(BUILD) DatasmithRevit2021 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2022-Linux-Debug:
	 $(BUILD) DatasmithRevit2022 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2022-Linux-DebugGame:
	 $(BUILD) DatasmithRevit2022 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2022-Linux-Shipping:
	 $(BUILD) DatasmithRevit2022 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2022-Linux-Test:
	 $(BUILD) DatasmithRevit2022 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2022:
	 $(BUILD) DatasmithRevit2022 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRhino6-Linux-Debug:
	 $(BUILD) DatasmithRhino6 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRhino6-Linux-DebugGame:
	 $(BUILD) DatasmithRhino6 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRhino6-Linux-Shipping:
	 $(BUILD) DatasmithRhino6 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRhino6-Linux-Test:
	 $(BUILD) DatasmithRhino6 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRhino6:
	 $(BUILD) DatasmithRhino6 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRhino7-Linux-Debug:
	 $(BUILD) DatasmithRhino7 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRhino7-Linux-DebugGame:
	 $(BUILD) DatasmithRhino7 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRhino7-Linux-Shipping:
	 $(BUILD) DatasmithRhino7 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRhino7-Linux-Test:
	 $(BUILD) DatasmithRhino7 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRhino7:
	 $(BUILD) DatasmithRhino7 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSDK-Linux-Debug:
	 $(BUILD) DatasmithSDK Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSDK-Linux-DebugGame:
	 $(BUILD) DatasmithSDK Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSDK-Linux-Shipping:
	 $(BUILD) DatasmithSDK Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSDK-Linux-Test:
	 $(BUILD) DatasmithSDK Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSDK:
	 $(BUILD) DatasmithSDK Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2019-Linux-Debug:
	 $(BUILD) DatasmithSketchUpRuby2019 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2019-Linux-DebugGame:
	 $(BUILD) DatasmithSketchUpRuby2019 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2019-Linux-Shipping:
	 $(BUILD) DatasmithSketchUpRuby2019 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2019-Linux-Test:
	 $(BUILD) DatasmithSketchUpRuby2019 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2019:
	 $(BUILD) DatasmithSketchUpRuby2019 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2020-Linux-Debug:
	 $(BUILD) DatasmithSketchUpRuby2020 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2020-Linux-DebugGame:
	 $(BUILD) DatasmithSketchUpRuby2020 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2020-Linux-Shipping:
	 $(BUILD) DatasmithSketchUpRuby2020 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2020-Linux-Test:
	 $(BUILD) DatasmithSketchUpRuby2020 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2020:
	 $(BUILD) DatasmithSketchUpRuby2020 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2021-Linux-Debug:
	 $(BUILD) DatasmithSketchUpRuby2021 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2021-Linux-DebugGame:
	 $(BUILD) DatasmithSketchUpRuby2021 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2021-Linux-Shipping:
	 $(BUILD) DatasmithSketchUpRuby2021 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2021-Linux-Test:
	 $(BUILD) DatasmithSketchUpRuby2021 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2021:
	 $(BUILD) DatasmithSketchUpRuby2021 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSolidworks2021-Linux-Debug:
	 $(BUILD) DatasmithSolidworks2021 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSolidworks2021-Linux-DebugGame:
	 $(BUILD) DatasmithSolidworks2021 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSolidworks2021-Linux-Shipping:
	 $(BUILD) DatasmithSolidworks2021 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSolidworks2021-Linux-Test:
	 $(BUILD) DatasmithSolidworks2021 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSolidworks2021:
	 $(BUILD) DatasmithSolidworks2021 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

HeadlessChaos-Linux-Debug:
	 $(BUILD) HeadlessChaos Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

HeadlessChaos-Linux-DebugGame:
	 $(BUILD) HeadlessChaos Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

HeadlessChaos-Linux-Shipping:
	 $(BUILD) HeadlessChaos Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

HeadlessChaos-Linux-Test:
	 $(BUILD) HeadlessChaos Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

HeadlessChaos:
	 $(BUILD) HeadlessChaos Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

HeadlessChaosPerf-Linux-Debug:
	 $(BUILD) HeadlessChaosPerf Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

HeadlessChaosPerf-Linux-DebugGame:
	 $(BUILD) HeadlessChaosPerf Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

HeadlessChaosPerf-Linux-Shipping:
	 $(BUILD) HeadlessChaosPerf Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

HeadlessChaosPerf-Linux-Test:
	 $(BUILD) HeadlessChaosPerf Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

HeadlessChaosPerf:
	 $(BUILD) HeadlessChaosPerf Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealLaunchDaemon-Linux-Debug:
	 $(BUILD) UnrealLaunchDaemon Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealLaunchDaemon-Linux-DebugGame:
	 $(BUILD) UnrealLaunchDaemon Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealLaunchDaemon-Linux-Shipping:
	 $(BUILD) UnrealLaunchDaemon Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealLaunchDaemon-Linux-Test:
	 $(BUILD) UnrealLaunchDaemon Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealLaunchDaemon:
	 $(BUILD) UnrealLaunchDaemon Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

LiveCodingConsole-Linux-Debug:
	 $(BUILD) LiveCodingConsole Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

LiveCodingConsole-Linux-DebugGame:
	 $(BUILD) LiveCodingConsole Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

LiveCodingConsole-Linux-Shipping:
	 $(BUILD) LiveCodingConsole Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

LiveCodingConsole-Linux-Test:
	 $(BUILD) LiveCodingConsole Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

LiveCodingConsole:
	 $(BUILD) LiveCodingConsole Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DsymExporter-Linux-Debug:
	 $(BUILD) DsymExporter Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DsymExporter-Linux-DebugGame:
	 $(BUILD) DsymExporter Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DsymExporter-Linux-Shipping:
	 $(BUILD) DsymExporter Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DsymExporter-Linux-Test:
	 $(BUILD) DsymExporter Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DsymExporter:
	 $(BUILD) DsymExporter Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4EditorServices-Linux-Debug:
	 $(BUILD) UE4EditorServices Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4EditorServices-Linux-DebugGame:
	 $(BUILD) UE4EditorServices Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4EditorServices-Linux-Shipping:
	 $(BUILD) UE4EditorServices Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4EditorServices-Linux-Test:
	 $(BUILD) UE4EditorServices Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4EditorServices:
	 $(BUILD) UE4EditorServices Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealAtoS-Linux-Debug:
	 $(BUILD) UnrealAtoS Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealAtoS-Linux-DebugGame:
	 $(BUILD) UnrealAtoS Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealAtoS-Linux-Shipping:
	 $(BUILD) UnrealAtoS Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealAtoS-Linux-Test:
	 $(BUILD) UnrealAtoS Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealAtoS:
	 $(BUILD) UnrealAtoS Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

ShaderCompileWorker-Linux-Debug:
	 $(BUILD) ShaderCompileWorker Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

ShaderCompileWorker-Linux-DebugGame:
	 $(BUILD) ShaderCompileWorker Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

ShaderCompileWorker-Linux-Shipping:
	 $(BUILD) ShaderCompileWorker Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

ShaderCompileWorker-Linux-Test:
	 $(BUILD) ShaderCompileWorker Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

ShaderCompileWorker:
	 $(BUILD) ShaderCompileWorker Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

SlateViewer-Linux-Debug:
	 $(BUILD) SlateViewer Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

SlateViewer-Linux-DebugGame:
	 $(BUILD) SlateViewer Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

SlateViewer-Linux-Shipping:
	 $(BUILD) SlateViewer Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

SlateViewer-Linux-Test:
	 $(BUILD) SlateViewer Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

SlateViewer:
	 $(BUILD) SlateViewer Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

SwitchboardListener-Linux-Debug:
	 $(BUILD) SwitchboardListener Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

SwitchboardListener-Linux-DebugGame:
	 $(BUILD) SwitchboardListener Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

SwitchboardListener-Linux-Shipping:
	 $(BUILD) SwitchboardListener Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

SwitchboardListener-Linux-Test:
	 $(BUILD) SwitchboardListener Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

SwitchboardListener:
	 $(BUILD) SwitchboardListener Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

TestPAL-Linux-Debug:
	 $(BUILD) TestPAL Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

TestPAL-Linux-DebugGame:
	 $(BUILD) TestPAL Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

TestPAL-Linux-Shipping:
	 $(BUILD) TestPAL Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

TestPAL-Linux-Test:
	 $(BUILD) TestPAL Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

TestPAL:
	 $(BUILD) TestPAL Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

TextureShareSDK-Linux-Debug:
	 $(BUILD) TextureShareSDK Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

TextureShareSDK-Linux-DebugGame:
	 $(BUILD) TextureShareSDK Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

TextureShareSDK-Linux-Shipping:
	 $(BUILD) TextureShareSDK Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

TextureShareSDK-Linux-Test:
	 $(BUILD) TextureShareSDK Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

TextureShareSDK:
	 $(BUILD) TextureShareSDK Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealCEFSubProcess-Linux-Debug:
	 $(BUILD) UnrealCEFSubProcess Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealCEFSubProcess-Linux-DebugGame:
	 $(BUILD) UnrealCEFSubProcess Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealCEFSubProcess-Linux-Shipping:
	 $(BUILD) UnrealCEFSubProcess Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealCEFSubProcess-Linux-Test:
	 $(BUILD) UnrealCEFSubProcess Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealCEFSubProcess:
	 $(BUILD) UnrealCEFSubProcess Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealFileServer-Linux-Debug:
	 $(BUILD) UnrealFileServer Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealFileServer-Linux-DebugGame:
	 $(BUILD) UnrealFileServer Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealFileServer-Linux-Shipping:
	 $(BUILD) UnrealFileServer Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealFileServer-Linux-Test:
	 $(BUILD) UnrealFileServer Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealFileServer:
	 $(BUILD) UnrealFileServer Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealFrontend-Linux-Debug:
	 $(BUILD) UnrealFrontend Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealFrontend-Linux-DebugGame:
	 $(BUILD) UnrealFrontend Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealFrontend-Linux-Shipping:
	 $(BUILD) UnrealFrontend Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealFrontend-Linux-Test:
	 $(BUILD) UnrealFrontend Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealFrontend:
	 $(BUILD) UnrealFrontend Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealHeaderTool-Linux-Debug:
	 $(BUILD) UnrealHeaderTool Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealHeaderTool-Linux-DebugGame:
	 $(BUILD) UnrealHeaderTool Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealHeaderTool-Linux-Shipping:
	 $(BUILD) UnrealHeaderTool Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealHeaderTool-Linux-Test:
	 $(BUILD) UnrealHeaderTool Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealHeaderTool:
	 $(BUILD) UnrealHeaderTool Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealInsights-Linux-Debug:
	 $(BUILD) UnrealInsights Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealInsights-Linux-DebugGame:
	 $(BUILD) UnrealInsights Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealInsights-Linux-Shipping:
	 $(BUILD) UnrealInsights Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealInsights-Linux-Test:
	 $(BUILD) UnrealInsights Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealInsights:
	 $(BUILD) UnrealInsights Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealLightmass-Linux-Debug:
	 $(BUILD) UnrealLightmass Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealLightmass-Linux-DebugGame:
	 $(BUILD) UnrealLightmass Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealLightmass-Linux-Shipping:
	 $(BUILD) UnrealLightmass Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealLightmass-Linux-Test:
	 $(BUILD) UnrealLightmass Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealLightmass:
	 $(BUILD) UnrealLightmass Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealMultiUserServer-Linux-Debug:
	 $(BUILD) UnrealMultiUserServer Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealMultiUserServer-Linux-DebugGame:
	 $(BUILD) UnrealMultiUserServer Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealMultiUserServer-Linux-Shipping:
	 $(BUILD) UnrealMultiUserServer Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealMultiUserServer-Linux-Test:
	 $(BUILD) UnrealMultiUserServer Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealMultiUserServer:
	 $(BUILD) UnrealMultiUserServer Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealPak-Linux-Debug:
	 $(BUILD) UnrealPak Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealPak-Linux-DebugGame:
	 $(BUILD) UnrealPak Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealPak-Linux-Shipping:
	 $(BUILD) UnrealPak Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealPak-Linux-Test:
	 $(BUILD) UnrealPak Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealPak:
	 $(BUILD) UnrealPak Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealRecoverySvc-Linux-Debug:
	 $(BUILD) UnrealRecoverySvc Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealRecoverySvc-Linux-DebugGame:
	 $(BUILD) UnrealRecoverySvc Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealRecoverySvc-Linux-Shipping:
	 $(BUILD) UnrealRecoverySvc Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealRecoverySvc-Linux-Test:
	 $(BUILD) UnrealRecoverySvc Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealRecoverySvc:
	 $(BUILD) UnrealRecoverySvc Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealVersionSelector-Linux-Debug:
	 $(BUILD) UnrealVersionSelector Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealVersionSelector-Linux-DebugGame:
	 $(BUILD) UnrealVersionSelector Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealVersionSelector-Linux-Shipping:
	 $(BUILD) UnrealVersionSelector Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealVersionSelector-Linux-Test:
	 $(BUILD) UnrealVersionSelector Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealVersionSelector:
	 $(BUILD) UnrealVersionSelector Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

BootstrapPackagedGame-Linux-Debug:
	 $(BUILD) BootstrapPackagedGame Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

BootstrapPackagedGame-Linux-DebugGame:
	 $(BUILD) BootstrapPackagedGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

BootstrapPackagedGame-Linux-Shipping:
	 $(BUILD) BootstrapPackagedGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

BootstrapPackagedGame-Linux-Test:
	 $(BUILD) BootstrapPackagedGame Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

BootstrapPackagedGame:
	 $(BUILD) BootstrapPackagedGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Client-Linux-Debug:
	 $(BUILD) UE4Client Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Client-Linux-DebugGame:
	 $(BUILD) UE4Client Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Client-Linux-Shipping:
	 $(BUILD) UE4Client Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Client-Linux-Test:
	 $(BUILD) UE4Client Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Client:
	 $(BUILD) UE4Client Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Editor-Linux-Debug:
	 $(BUILD) UE4Editor Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Editor-Linux-DebugGame:
	 $(BUILD) UE4Editor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Editor-Linux-Shipping:
	 $(BUILD) UE4Editor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Editor-Linux-Test:
	 $(BUILD) UE4Editor Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Editor:
	 $(BUILD) UE4Editor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Game-Linux-Debug:
	 $(BUILD) UE4Game Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Game-Linux-DebugGame:
	 $(BUILD) UE4Game Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Game-Linux-Shipping:
	 $(BUILD) UE4Game Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Game-Linux-Test:
	 $(BUILD) UE4Game Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Game:
	 $(BUILD) UE4Game Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Server-Linux-Debug:
	 $(BUILD) UE4Server Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Server-Linux-DebugGame:
	 $(BUILD) UE4Server Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Server-Linux-Shipping:
	 $(BUILD) UE4Server Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Server-Linux-Test:
	 $(BUILD) UE4Server Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Server:
	 $(BUILD) UE4Server Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
